<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_flights_btn</name>
   <tag></tag>
   <elementGuidId>ce88add6-b6df-4b2a-af8e-14e7ff291504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-18t94o4.css-1dbjc4n.r-kdyh1x.r-1loqt21.r-eu3ka.r-1jj8364.r-10paoce.r-1e081e0.r-5njf8e.r-1otgn73.r-lrvibr.r-17x6qj0.r-1wyyakw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div[2]/div/div[2]/div[3]/div/div/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f286b87-0024-48f6-adc4-f026d17988cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>23ed4837-ae1b-4b52-9737-2c40fffbfc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>751a6226-38d4-4531-9ff2-662f176bbb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cab3b094-3a6c-4ced-a343-16b39dff177e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18t94o4 css-1dbjc4n r-kdyh1x r-1loqt21 r-eu3ka r-1jj8364 r-10paoce r-1e081e0 r-5njf8e r-1otgn73 r-lrvibr r-17x6qj0 r-1wyyakw</value>
      <webElementGuid>47b485cc-7672-4b67-9abb-9f0b18dd998f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>desktop-default-search-button</value>
      <webElementGuid>6cfb84d5-c026-43c8-836e-8f5ace7e5825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search FlightsSearch Flights</value>
      <webElementGuid>476da4ed-7381-44dd-a04d-bac7938cf82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-axzv8h r-l13dpy&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-rs99b7 r-1yos0t3 r-1xfddsp r-bztko3 r-uwe93p r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-1xfddsp&quot;]/div[@class=&quot;css-1dbjc4n r-u6sd8q r-4gszlv r-1f0042m r-13awgt0 r-1xfddsp r-1ygmrgt r-bnwqim&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1wh2hl7 r-e65k4z r-1q9bdsx r-xyw6el&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1pn2ns4&quot;]/div[@class=&quot;css-18t94o4 css-1dbjc4n r-kdyh1x r-1loqt21 r-eu3ka r-1jj8364 r-10paoce r-1e081e0 r-5njf8e r-1otgn73 r-lrvibr r-17x6qj0 r-1wyyakw&quot;]</value>
      <webElementGuid>eb57d132-0de9-44c5-b03a-f8940bc1b16e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div[2]/div/div[2]/div[3]/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>e381535b-fb21-4fe1-892d-716711097d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Class'])[1]/following::div[1]</value>
      <webElementGuid>fdaa0f4f-ad3a-49b9-b23c-24932a8a1166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/following::div[5]</value>
      <webElementGuid>9456d866-df5c-47f5-9925-6e82cd72a03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Alerts'])[1]/preceding::div[5]</value>
      <webElementGuid>b0913f18-c856-418d-8a8e-3492939dd646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>eefe68e0-361a-440b-8f1c-67002b370a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Search FlightsSearch Flights' or . = 'Search FlightsSearch Flights')]</value>
      <webElementGuid>4c6ad8b4-4265-4b1a-91c1-14c89e2d8d3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
